[build]
target = "arm-unknown-linux-musleabi"

[target.arm-unknown-linux-musleabi]
linker = "arm-hisiv100nptl-linux-gcc"
runner = "./target-runner.sh"
rustflags = [
  "-C", "target-cpu=cortex-a9",
  "-C", "target-feature=+soft-float,-neon,+v7,+vfp3,+d16",
  "-C", "link-arg=-march=armv7-a",
  "-C", "link-arg=-mcpu=cortex-a9",
  "-C", "link-arg=-mfloat-abi=softfp",
  "-C", "link-arg=-mfpu=vfpv3-d16",
]
